import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, Phone } from "lucide-react";
import { SiteFooter, defaultSocialLinks } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { navItems } from "@/data/nav";
import type { Service } from "@/types/service";

export function ServiceDetail({ service }: { service: Service }) {
  return <main className="site-shell service-detail-page"><SiteHeader menuItems={navItems} hotline={service.hotline} ctaLabel="Thuê xe ngay" ctaHref="/#booking" /><section className="service-detail-hero"><div><Link className="back-link" href="/dich-vu"><ArrowLeft aria-hidden="true" /> Tất cả dịch vụ</Link><p className="eyebrow"><span className="eyebrow-line" /> DỊCH VỤ THEO NHU CẦU</p><h1>{service.name}<br /><em>đúng cách.</em></h1><p className="detail-summary">{service.shortDescription}</p></div><div className="service-detail-mark"><span>XE MIỀN NAM</span><strong>{service.iconLabel}</strong><small>ĐI TỬ TẾ TRÊN MỌI HÀNH TRÌNH</small></div></section><section className="service-detail-content section-wrap"><div className="service-description"><p className="section-label">VÌ SAO CHỌN DỊCH VỤ NÀY</p><h2>Được chuẩn bị<br />cho điều bạn cần.</h2><p>{service.detailDescription}</p></div><div className="service-detail-sections"><section><p className="section-label">LOẠI XE PHÙ HỢP</p><div className="service-type-list">{service.vehicleTypes.map((type) => <Link href={`/loai-xe/${type.slug}`} className="service-type-card" key={type.slug}><div><h3>{type.name}</h3><p>{type.description}</p></div><ArrowRight aria-hidden="true" /></Link>)}</div></section>{service.suggestedVehicles.length > 0 && <section><p className="section-label">XE GỢI Ý CỤ THỂ</p><div className="suggested-vehicle-list">{service.suggestedVehicles.map((vehicle) => <Link href={`/doi-xe/${vehicle.slug}`} className="suggested-vehicle-card" key={vehicle.slug}><span className="suggested-vehicle-dot" /><div><h3>{vehicle.name}</h3><p>{vehicle.detail}</p></div><ArrowRight aria-hidden="true" /></Link>)}</div></section>}<section><p className="section-label">LƯU Ý RIÊNG CHO DỊCH VỤ NÀY</p><ul className="service-notes">{service.notes.map((note) => <li key={note}><Check aria-hidden="true" /> <span>{note}</span></li>)}</ul></section></div></section><section className="service-cta section-wrap"><div><p className="section-label">CẦN TƯ VẤN THÊM?</p><h2>Hãy kể chúng tôi<br /><em>ngày bạn cần đi.</em></h2></div><div className="service-cta-actions"><a className="button button-dark" href={`tel:${service.hotline.replace(/\s/g, "")}`}><Phone aria-hidden="true" /> Gọi {service.hotline}</a><Link className="button button-accent" href="/lien-he">Gửi yêu cầu tư vấn <ArrowRight aria-hidden="true" /></Link></div></section><SiteFooter tagline={<>Đi đâu cũng có Xe Miền Nam.<br />Kết nối những hành trình tử tế.</>} phone={service.hotline} linkGroups={[{ title: "KHÁM PHÁ", links: [{ label: "Tuyến đường", href: "/tuyen-duong" }, { label: "Đội xe", href: "/doi-xe" }, { label: "Dịch vụ", href: "/dich-vu" }] }, { title: "HỖ TRỢ", links: [{ label: "Câu hỏi thường gặp", href: "#" }, { label: "Liên hệ", href: "/lien-he" }] }]} socialLinks={defaultSocialLinks} copyright="© 2026 Xe Miền Nam" madeFor="Made for the road." /></main>;
}
