import Link from "next/link";
import { ArrowRight, BusFront, Check, MapPin, ShieldCheck } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter, defaultSocialLinks } from "@/components/site-footer";
import { navItems } from "@/data/nav";
import { VehicleCard } from "@/components/vehicle-results";
import type { Vehicle } from "@/types/vehicle";
import type { VehicleCategory } from "@/data/vehicle-categories";

const footerLinkGroups = [{ title: "KHÁM PHÁ", links: [{ label: "Tuyến đường", href: "/tuyen-duong" }, { label: "Đội xe", href: "/doi-xe" }, { label: "Loại xe", href: "/loai-xe" }] }, { title: "HỖ TRỢ", links: [{ label: "Câu hỏi thường gặp", href: "#" }, { label: "Liên hệ", href: "/#booking" }] }];

function VehicleArt({ category }: { category: VehicleCategory }) { return <div className={`vehicle-type-art vehicle-art ${category.color}`} role="img" aria-label={`${category.label} - ${category.title}`}><BusFront /><span>{category.label}</span></div>; }

export function VehicleTypeLanding({ category, vehicles, detail = false }: { category: VehicleCategory; vehicles: Vehicle[]; detail?: boolean }) {
  return <main className="site-shell vehicle-type-page"><SiteHeader menuItems={navItems} hotline="1900 6789" ctaLabel="Thuê xe ngay" ctaHref="/#booking" />
    <section className="vehicle-type-hero section-wrap"><div className="vehicle-type-hero-copy"><Link className="back-link" href={detail ? "/loai-xe" : "/doi-xe"}>← {detail ? "Tất cả loại xe" : "Xem đội xe"}</Link><p className="eyebrow"><span className="eyebrow-line" /> {category.label}</p><h1>{category.title}</h1><p>{category.description}</p><Link className="button button-primary" href="/#booking">Tư vấn lịch trình <ArrowRight size={16} /></Link></div><VehicleArt category={category} /></section>
    <section className="section-wrap vehicle-type-intro"><div><p className="section-label">PHÙ HỢP VỚI BẠN</p><h2>Đi đúng nhu cầu, nhẹ đầu cả chuyến đi.</h2></div><div className="vehicle-type-bullets">{category.audience.map((item) => <span key={item}><ShieldCheck /> {item}</span>)}</div></section>
    <section className="section-wrap vehicle-type-amenities"><p className="section-label">TIỆN ÍCH TRÊN XE</p><div className="vehicle-type-amenity-grid">{category.amenities.map((item) => <div key={item}><Check /><strong>{item}</strong><p>Được chuẩn bị để hành trình thoải mái hơn từ lúc khởi hành.</p></div>)}</div></section>
    {detail && <><section className="section-wrap vehicle-type-vehicles"><div className="section-heading-row"><div><p className="section-label">XE ĐANG CÓ</p><h2>Chọn chiếc xe hợp với hành trình.</h2></div><Link href="/doi-xe" className="text-link">Xem toàn bộ đội xe <ArrowRight size={15} /></Link></div><div className="vehicle-grid vehicle-type-grid">{vehicles.map((vehicle) => <VehicleCard key={vehicle.id} vehicle={vehicle} />)}</div></section><section className="section-wrap vehicle-type-routes"><div><p className="section-label">GIÁ THAM KHẢO</p><h2>Một vài tuyến được chọn nhiều.</h2></div><div className="vehicle-price-table">{vehicles.flatMap((vehicle) => vehicle.routePrices).slice(0, 3).map((item, index) => <div className="vehicle-price-row" key={`${item.route}-${index}`}><span>{item.route}</span><strong>{item.price}</strong><small>{item.note}</small></div>)}</div></section></>}
    {!detail && <section className="section-wrap vehicle-category-grid"><div className="section-heading-row"><div><p className="section-label">CHỌN THEO NHU CẦU</p><h2>Bốn cách để bắt đầu một chuyến đi.</h2></div></div><div className="vehicle-category-cards">{[category].map((item) => <Link href={`/loai-xe/${item.slug}`} className="vehicle-category-card" key={item.slug}><VehicleArt category={item} /><div><p>{item.label}</p><h3>{item.title}</h3><span>Khám phá loại xe <ArrowRight size={15} /></span></div></Link>)}</div></section>}
    {detail && <section className="section-wrap vehicle-type-services"><p className="section-label">DỊCH VỤ ĐI KÈM</p><div className="vehicle-service-grid">{category.services.map((service) => <Link href={service.href} className="vehicle-service-card" key={service.title}><MapPin /><h3>{service.title}</h3><p>{service.description}</p><ArrowRight /></Link>)}</div></section>}
    <section className="vehicle-type-cta"><div><p className="section-label">SẴN SÀNG LÊN ĐƯỜNG?</p><h2>Cho chúng tôi biết bạn cần đi đâu.</h2><p>Nhận tư vấn xe và lịch trình phù hợp trong một cuộc gọi.</p></div><Link className="button button-primary" href="/#booking">Đặt xe ngay <ArrowRight size={16} /></Link></section><SiteFooter tagline="Đưa bạn đi xa, theo cách nhẹ nhàng hơn." phone="1900 6789" linkGroups={footerLinkGroups} socialLinks={defaultSocialLinks} copyright="© 2024 Xe Miền Nam" madeFor="Đi xa thật dễ." /></main>;
}

export function VehicleCategoryIndex({ categories }: { categories: VehicleCategory[] }) { return <main className="site-shell vehicle-type-page"><SiteHeader menuItems={navItems} hotline="1900 6789" ctaLabel="Thuê xe ngay" ctaHref="/#booking" /><section className="vehicle-type-index-hero section-wrap"><p className="eyebrow"><span className="eyebrow-line" /> CHỌN ĐÚNG CHIẾC XE</p><h1>Mỗi hành trình,<br /><em>một lựa chọn vừa vặn.</em></h1><p>Khám phá các nhóm xe được thiết kế cho từng kiểu chuyến đi — từ gia đình nhỏ đến đoàn lớn.</p></section><section className="section-wrap vehicle-category-grid"><div className="vehicle-category-cards vehicle-category-cards-four">{categories.map((category) => <Link href={`/loai-xe/${category.slug}`} className="vehicle-category-card" key={category.slug}><VehicleArt category={category} /><div><p>{category.label}</p><h3>{category.title}</h3><span>Xem loại xe <ArrowRight size={15} /></span></div></Link>)}</div></section><SiteFooter tagline="Đưa bạn đi xa, theo cách nhẹ nhàng hơn." phone="1900 6789" linkGroups={footerLinkGroups} socialLinks={defaultSocialLinks} copyright="© 2024 Xe Miền Nam" madeFor="Đi xa thật dễ." /></main>; }
